apiVersion: v1
entries:
  qcloudy-common-app:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-12-26T05:32:52.953758+06:00"
    description: qcloudy-common-app
    digest: 068e00054d0d487fcc18c95b99852ea3d7161ec907e5672ed55349305c2063c2
    maintainers:
    - email: marat@qcloudy.io
      name: Okassov Marat
    name: qcloudy-common-app
    urls:
    - qcloudy-common-app-1.0.0.tgz
    version: 1.0.0
generated: "2021-12-26T05:32:52.952824+06:00"
